### ISSUE TITLE
Build a Nodejs client listening to the currency price

### ISSUE THREAD

**Issue by YuqingCheng** [YuqingCheng/cs5610-project-2#6]
Build a Nodejs client listening to the currency price, use websocket to connect the nodejs client with our phoenix server.

Auto-email handling will be implemented through channel actions, use Bamboo to broadcast emails.

Use phoenix-channels to build websocket: https://www.npmjs.com/package/phoenix-channels

**Comment by Cappuccinuo** [comment]
Is there any difference between package-lock.json and package.json? I think have to upload package.json

**Comment by YuqingCheng** [comment]
Thank you for mentioning this, I have added package.json, please try npm install again
