### ISSUE TITLE
add feature of login with facebook

### ISSUE THREAD

**Issue by YuqingCheng** [YuqingCheng/cs5610-project-2#7]
enable user to login with facebook:
https://developers.facebook.com/docs/facebook-login/web

**Comment by Joyce-Zhao** [comment]
Updated deps. 
Some errors after choosing google account to sign in.
Followed tutorial: https://medium.brianemory.com/elixir-phoenix-creating-an-app-part-4-using-google-%C3%BCberauth-e7d2ed1a3541
Another tutorial might be helpful: http://www.binarywebpark.com/google-oauth-authentication-phoenix-elixir/
Will debug later.

**Comment by Joyce-Zhao** [comment]
Added .env to .gitignore
Now, to get our local environment variables to work, in your terminal type
`source .env`
(you will need to do this for each terminal window you are using).
